FROM node:22

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

WORKDIR /app

# ===package.json作成後にコメントアウトを外す===
COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3001"]